package hust.soict.hedspi.aims.gui;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Admin
 */
public class Aims extends javax.swing.JFrame {

    /**
     * Creates new form Aims
     */
    public Aims() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CreatejMenu = new javax.swing.JMenuItem();
        AddjMenu = new javax.swing.JMenuItem();
        DeletejMenu = new javax.swing.JMenuItem();
        DisplayjMenu = new javax.swing.JMenuItem();
        ExitjMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        CreatejMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        CreatejMenu.setText("Create");
        CreatejMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatejMenuActionPerformed(evt);
            }
        });
        jMenu1.add(CreatejMenu);

        AddjMenu.setText("Add");
        AddjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddjMenuActionPerformed(evt);
            }
        });
        jMenu1.add(AddjMenu);

        DeletejMenu.setText("Delete");
        DeletejMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletejMenuActionPerformed(evt);
            }
        });
        jMenu1.add(DeletejMenu);

        DisplayjMenu.setText("Display");
        jMenu1.add(DisplayjMenu);

        ExitjMenu.setText("Exit");
        ExitjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitjMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ExitjMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("User");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Help");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreatejMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatejMenuActionPerformed
        // TODO add your handling code here:
        new CreateFrame().setVisible(true);
        this.dispose();
        
      
    }//GEN-LAST:event_CreatejMenuActionPerformed

    private void DeletejMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletejMenuActionPerformed
        // TODO add your handling code here:
         new DeleteFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DeletejMenuActionPerformed

    private void AddjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddjMenuActionPerformed
        // TODO add your handling code here:
         new AddFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddjMenuActionPerformed

    private void ExitjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitjMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aims().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddjMenu;
    private javax.swing.JMenuItem CreatejMenu;
    private javax.swing.JMenuItem DeletejMenu;
    private javax.swing.JMenuItem DisplayjMenu;
    private javax.swing.JMenuItem ExitjMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
